### ISSUE TITLE
not compatible with lens 6.0

### ISSUE THREAD

**Issue by bogdanioanliviu** [aquasecurity/trivy-operator-lens-extension#20]
In the last lens version this extension it's not compatible.

**Comment by poobah** [comment]
You can manually patch and build this yourself for now. If you clone the repo and edit the package.json to

  "engines": {
    "lens": "^6.0.0"
  }

Then build and package as described in the readme.

**Comment by bogdanioanliviu** [comment]
Thank you that worked.
